defaults:
  - default


_target_: SafeDiffuser.diffuser.models.diffusion.SafeGaussianDiffusion
model_bone:
  _target_: SafeDiffuser.diffuser.models.temporal.TemporalUnet
  horizon: ${max_seq}
  transition_dim: ${x_dim}
  cond_dim: ${x_dim}
  dim_mults: [1, 4, 8]
# model_bone:
#   _target_: model.dit.TrajectoryDiTConditional
#   x_dim: ${x_dim} # 0+x_dim
#   cond_dim: ${x_dim}
#   max_horizon: ${max_seq}
#   hidden_dim: 128
#   depth: 4
#   num_heads: 4
#   time_embed_dim: 128
horizon: ${max_seq}
observation_dim: ${x_dim}
action_dim: 0
n_timesteps: ${steps}  # diffusion steps
loss_type: 'l2'
clip_denoised: true
predict_epsilon: false
action_weight: 0
loss_weights: null # None
loss_discount: 1
safe_method: ${sample.method}

