defaults:
  - default


_target_: model.new_model.PolytopeConstrainedFlowModel
x_dim: ${x_dim}
num_cons: ${num_cons}
num_rays: ${num_rays}
max_seq: ${max_seq}
embed_dim: 128
num_heads_cons: 4
num_layers_cons: 2
num_heads_traj: 4
num_layers_traj: 2
num_heads_weight: 4
num_layers_weight: 2
time_embed_scale: 1000
use_block_mask_cons: true
use_block_mask_cross: true
device: ${train.device}