
env_name: "test"
algo_name: "test"
run_name: "test" # current run
seed: 42
device: "cuda:0"


optimizer:
  _target_: torch.optim.Adam
  # _partial_: true  
  lr: ${train.lr}

lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${train.iteration}
  eta_min: 1e-6

train_dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: ${train.batch_size}
  shuffle: true

val_dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: ${train.batch_size}
  shuffle: true

hydra:
  run:
    dir: outputs/${env_name}/${algo_name}_${run_name}/${seed}_${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: true  