
# Hydra 配置: 决定日志保存在哪里
hydra:
  run:
    # 动态生成目录
    dir: outputs/${env_name}/${algo_name}_${run_name}/${seed}_${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: true  # 进入输出目录运行 (这样产生的 tensorboard 就在该目录下)