defaults:
  - sample_RoS_hopper
  - _self_

env:
  use_cpx: true
  vel_scale: ${vel_scale}  

env_name: hoppercpx
algo_name: GD
run_name: sample

height_limit: 1.6
vel_scale: 0.01

algorithm:
  env_name: "hopper_cpx"
  safe_method: "GD"