defaults:
  - default
  - backbone: poly
  - algorithm: discrete_flow
  - env: walker2d
  - _self_

dataset:
  _target_: src.datasets.constrained_dataset.ConstrainedMinariDataset
  # 约束相关
  full_constrained_idx: ${full_constrained_idxs}
  single_A: ${single_A}
  single_b: ${single_b}

  env: ${dataset_minari_name}
  horizon: ${horizon}
  normalizer: 'GaussianNormalizer'
  preprocess_fns: []
  max_path_length: ${max_seq}
  max_n_episodes: 10000
  termination_penalty: 0
  use_padding: false

algorithm:
  action_weight: 10.0
  loss_discount: 0.99

env:
  use_cpx: ${use_cpx}
  vel_scale: ${vel_scale}
  height_limit: ${height_limit}
  height_min: ${height_min}
  v_max: ${v_max}
  v_min: ${v_min}

backbone:
  share_traj_encoder: true

  
# 不加 guide policy config
policy:
  _target_: src.sampling.policies.PolyFlowPolicy
  preprocess_fns: []


val_dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: ${eval.samples}
  shuffle: true

eval:
  load_model_path: "outputs/walker2dcpx/polyflow_train/42_2026-01-07_17-48-08/state_final.pt"
  load_ema: false
  samples: 200   # 计算分布差异时，采样多少个horizon
  # rollout
  n_episodes: 10  # rollout 多少条轨迹
  seed: ${seed}
  is_video: true
  video_episodes: 2

  check_index_list: [0, 1, 2, 3, 4, 5, 6, 7] # 在计算平滑度时考虑哪些维度



env_name: walker2dcpx
algo_name: polyflow
run_name: sample


device: "cuda:0"
seed: 42
dataset_minari_name: "mujoco/walker2d/medium-v0"
horizon: 100  # 如果要使用 unet 要保证 horizon 能够被8整除
max_seq: 1000
obs_dim: 17
act_dim: 6
transition_dim: 23
cond_dim: 17
steps: 10  # 采样步数


height_limit: 1.35
height_min: 0.8
v_max: 3
v_min: -3
vel_scale: 0.01
use_cpx: 1
full_constrained_idxs: [6, 15] # 对应walker2d 的z height, z vel
single_A: [[1, 0.01], [1, 0], [-1, 0], [0, 1], [0, -1]]
single_b: [1.35, 1.35, -0.8, 3, 3]
num_cons: 5



