defaults:
  - time_polyflow_walkercpx2
  - _self_

backbone:
  time_invariance_cons: true

eval:
  load_model_path: "outputs/walker2dcpx2/polyflow_train_fixcons/42_2026-01-17_17-14-07/state_final.pt"
  load_ema: false
  samples: 200   # 计算分布差异时，采样多少个horizon
  # rollout
  n_episodes: 10  # rollout 多少条轨迹
  seed: ${seed}
  is_video: true
  video_episodes: 2
  skip_rollout: true

  check_index_list: [0, 1, 2, 3, 4, 5, 6, 7] # 在计算平滑度时考虑哪些维度



env_name: walker2dcpx2
algo_name: polyflow
run_name: time_fixcons


device: "cuda:0"
seed: 42

steps: 10  # 采样步数