defaults:
  - time_polyflow_hoppercpx
  - _self_

backbone:
  time_invariance_cons: true


eval:
  load_model_path: "outputs/hoppercpx/polyflow_train_fixcons_ot/42_2026-01-19_13-00-00/state_final.pt"
  load_ema: true
  samples: 200   # 计算分布差异时，采样多少个horizon
  # rollout
  n_episodes: 10  # rollout 多少条轨迹
  seed: ${seed}
  is_video: true
  video_episodes: 2
  skip_rollout: true

  check_index_list: [0, 1, 2, 3, 4] # 在计算平滑度时考虑哪些维度



env_name: hoppercpx
algo_name: polyflow
run_name: time_fixcons_ot


device: "cuda:0"
seed: 42

steps: 10  # 采样步数