defaults:
  - time_flow_hoppercpx2

algorithm:
  _target_: src.models.flow.SafeFlowMathcing
  horizon: ${horizon}
  observation_dim: ${obs_dim}
  action_dim: ${act_dim}
  n_timesteps: ${steps}
  loss_type: 'l2'
  action_weight: 10
  loss_discount: 1.0
  loss_weights: null
  env_name: "hopper_cpx2"
  safe_method: "safeflow"
  height_limit: ${height_limit}
  vel_scale: ${vel_scale}
  obs_vel_idx: 6
  height_min: ${height_min}
  v_max: ${v_max}
  v_min: ${v_min}

env_name: hoppercpx2
algo_name: safeflow
run_name: time_step200

device: "cuda:0"
seed: 42

height_limit: 1.5
vel_scale: 0.01
height_min: 0.8
v_max: 2.5
v_min: -2.5
use_cpx: 2
steps: 200

