

defaults:
  - dataset: box_constraint
  - env: maze2d
  - model: dit
  - default
  - _self_  # 允许主配置覆盖默认值

# 实验名称 (用于文件夹命名)
env_name: "maze2d"
algo_name: "flow"
run_name: "train" # 这次实验的名字
seed: 42
device: "cuda:0"

x_dim: 2
num_cons: 4
max_seq: 300
steps: 200 # 离散步数

file_path: "data/large_maze_traj_data_expand_02.npz"

# 采样参数
sample:
  method: "flow" # discrete, flow, diffusion
  steps: ${steps}
  device: ${device}
  projection: "none"


# 训练超参数
train:
  method: "flow" # discrete, flow, diffusion
  iteration: 10000 # 训练steps
  lr: 1e-4
  batch_size: 100
  steps: ${steps}        # 离散时间步数
  eval_freq: 1000
  log_freq: 100
  save_freq: 5000
  device: ${device}
  seed: ${seed}

eval:
  eval_samples: 100
  plot_ellips: false
  max_plot_traj: 5



