defaults:
  - default
  - dataset: sequence_value
  - backbone: valuefunction
  - algorithm: valuediffusion
  - env: hopper
  - _self_


trainer:
  _target_: src.utils.training.Trainer
  # diffusion_model: ??
  # dataset: ??
  # renderer: null
  device: ${device}
  ema_decay: 0.995
  train_batch_size: 32
  train_lr: 2e-4
  gradient_accumulate_every: 2
  step_start_ema: 2000
  update_ema_every: 10
  log_freq: 500
  save_freq: 20000
  label_freq: ${trainer.save_freq}
  save_parallel: false


env_name: hopper
algo_name: diffusionvalue
run_name: train


device: "cuda:2"
seed: 42
dataset_minari_name: "mujoco/hopper/medium-v0"
horizon: 600  # 如果要使用 unet 要保证 horizon 能够被8整除
max_seq: 1000
obs_dim: 11
act_dim: 3
transition_dim: 14
cond_dim: 11
steps: 20  # diffusion 扩散步

iteration: 200000  # 训练step

height_limit: 1.5