defaults:
  - default
  - dataset: sequence_value
  - backbone: valuefunction
  - algorithm: valuediffusion
  - env: walker2d
  - _self_

env:
  use_cpx: 0

trainer:
  _target_: src.utils.training.Trainer
  device: ${device}
  ema_decay: 0.995
  train_batch_size: 32
  train_lr: 2e-4
  gradient_accumulate_every: 2
  step_start_ema: 2000
  update_ema_every: 10
  log_freq: 500
  save_freq: 20000
  label_freq: ${trainer.save_freq}
  save_parallel: false


env_name: walker2d
algo_name: diffusionvalue
run_name: train


device: "cuda:1"
seed: 42
dataset_minari_name: "mujoco/walker2d/medium-v0"
horizon: 600  # 如果要使用 unet 要保证 horizon 能够被8整除
max_seq: 1000
obs_dim: 17
act_dim: 6
transition_dim: 23
cond_dim: 17
steps: 20  # diffusion 扩散步

iteration: 200000  # 训练step
