defaults:
  - train_polyflow_walkercpx2_fixcons
  - _self_

algorithm:
  use_ot_batch: true

env_name: walker2dcpx2
algo_name: polyflow
run_name: train_fixcons_ot


device: "cuda:2"
seed: 42

steps: 10  # 采样步数