

defaults:
  - dataset: batch_invariance_constraint
  - env: lmaze
  - model: dit
  - default
  - _self_  


env_name: "lmaze"
algo_name: "flow"
run_name: "train" # current run
seed: 42
device: "cuda:1"

x_dim: 2
num_cons: 4
max_seq: 50
steps: 200 

file_path: "data/L_maze_traj_data.npz" 


sample:
  method: "flow" # discrete, flow, diffusion
  steps: ${steps}
  device: ${device}
  projection: "none" # classifier_guidance, none, truncation



train:
  method: "flow" # discrete, flow, diffusion
  iteration: 10000 # training steps
  lr: 1e-4
  batch_size: 50
  steps: ${steps}        
  eval_freq: 1000
  log_freq: 100
  save_freq: 5000
  device: ${device}
  seed: ${seed}

eval:
  eval_samples: 100
  plot_ellips: false
  max_plot_traj: 5



