defaults:
  - default


_target_: src.models.dit.TrajectoryFlowConditional
x_dim: ${transition_dim}
cond_dim: ${obs_dim}
max_horizon: ${horizon}
hidden_dim: 128
depth: 4
num_heads: 4
time_embed_dim: 128