defaults:
  - default

_target_: src.datasets.go2_dataset.LeggedRobotDataset
file_path: ${file_path}
horizon: ${horizon}
normalizer: 'GaussianNormalizer'
max_path_length: ${max_seq}
max_n_episodes: 10000
termination_penalty: 0
use_padding: false