defaults:
  - default

_target_: src.datasets.constrained_dataset.BoxConstrainedMinariDataset
# 约束相关
obs_constrained_idx: ${obs_constrained_idx}
single_A: ${single_A}
single_b: ${single_b}

env: ${dataset_minari_name}
horizon: ${horizon}
normalizer: 'GaussianNormalizer'
preprocess_fns: []
max_path_length: ${max_seq}
max_n_episodes: 10000
termination_penalty: 0
use_padding: true
